version: '3'

services:
  nginx:
    image: "nginx:stable"
    container_name: "nginx_lzyyy_testserve"
    volumes:
      - ./conf:/etc/nginx/conf.d:ro
      - ./../out:/var/www:ro
    ports:
      - 80:80